import { getSeoPageByUrl } from './seo-registry-mock';

export interface GeneratedPageContent {
  hero: {
    h1: string;
    subheading: string;
    ctaPrimary: string;
    ctaSecondary: string;
    trustLine: string;
  };
  context: {
    heading: string;
    body: string;
  };
  captureList: string[];
  deliverablesList: string[];
  recommendedBundle: {
    name: string;
    slug: string;
    description: string;
  };
  relatedServices: { name: string; slug: string }[];
  localOrSectorConsiderations: {
    heading: string;
    items: string[];
  };
  faqs: { question: string; answer: string }[];
  finalCta: {
    headline: string;
    body: string;
    cta: string;
  };
}

export function buildSeoPageContent(url: string, locationSlug?: string, sectorSlug?: string, serviceSlug?: string, outcomeSlug?: string): GeneratedPageContent | null {
  const pageDef = getSeoPageByUrl(url);
  if (!pageDef || pageDef.indexabilityStatus !== 'Index') {
    return null; // Page not found or shouldn't be rendered publicly
  }

  const serviceName = serviceSlug ? serviceSlug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') : '';
  const locationName = locationSlug ? locationSlug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') : '';
  const sectorName = sectorSlug ? sectorSlug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') : '';
  const outcomeName = outcomeSlug ? outcomeSlug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') : '';

  // This is a naive builder just for the mock setup. 
  // In a real DB, these fields would be explicitly stored or generated by an LLM pipeline and saved.
  return {
    hero: {
      h1: pageDef.h1,
      subheading: pageDef.metaDescription,
      ctaPrimary: 'Start Project Brief',
      ctaSecondary: 'View Commercial Packages',
      trustLine: 'CAA-compliant operations • GVC-qualified pilots • Fully insured commercial drone services'
    },
    context: {
      heading: `Why ${serviceName || outcomeName} matters ${locationName ? `in ${locationName}` : ''} ${sectorName ? `for ${sectorName}` : ''}`,
      body: `EntireFM Drone provides specialist aerial capture and visual data. We structure the drone operation around the required output, selecting the right capture method, sensor, workflow and deliverable. ${
        locationName ? `Operating in ${locationName}, we manage local airspace and site constraints to deliver safe, compliant operations.` : ''
      } ${
        sectorName ? `For ${sectorName} professionals, this means actionable visual evidence to support your operational workflows without defaulting to traditional high-risk access methods.` : ''
      }`
    },
    captureList: [
      'High-level visual condition',
      'Access-restricted areas',
      'Contextual site overview',
      'Specific asset features',
      'Key measurements where scoped'
    ],
    deliverablesList: [
      'High-resolution image set',
      'PDF visual summary',
      'Raw capture data',
      'Annotated evidence pack'
    ],
    recommendedBundle: {
      name: 'Visual Output Pack',
      slug: 'visual-sales-pack',
      description: 'A standard bundle of visual deliverables for immediate use.'
    },
    relatedServices: [
      { name: 'Drone Inspection', slug: 'drone-inspection' },
      { name: 'Surveying & Mapping', slug: 'surveying-mapping' },
      { name: 'Aerial Photography & Film', slug: 'aerial-photography-film' }
    ],
    localOrSectorConsiderations: {
      heading: 'Operational Considerations',
      items: [
        'Airspace restrictions and permissions',
        'Site access and takeoff locations',
        'Weather and operational windows',
        'Public proximity and safety buffers'
      ]
    },
    faqs: [
      {
        question: `Do you provide ${serviceName || outcomeName} ${locationName ? `in ${locationName}` : ''}?`,
        answer: `Yes, EntireFM Drone supports commercial drone projects ${locationName ? `in ${locationName} and the surrounding area` : 'across the UK'}, subject to airspace and site feasibility.`
      },
      {
        question: `How quickly can this be delivered?`,
        answer: `Rapid deployment is possible depending on the site. If the location requires specific permissions or stakeholder coordination, lead times will vary.`
      },
      {
        question: `What deliverables do we receive?`,
        answer: `Deliverables are scoped prior to flight but typically include high-resolution imagery, video, mapping data or visual summaries depending on the required outcome.`
      }
    ],
    finalCta: {
      headline: `Need ${serviceName || outcomeName || 'Drone Services'} ${locationName ? `in ${locationName}` : ''}?`,
      body: 'Tell us what you need to inspect, measure, monitor, film or visualise. EntireFM Drone will review the site, required output and operational constraints before recommending the right capture route.',
      cta: 'Start Project Brief'
    }
  };
}
